[package]
name = "just_enough_vcs_cli"
edition = "2024"
build = "build.rs"
authors = ["JustEnoughVCS Team"]
homepage = "https://github.com/JustEnoughVCS/CommandLine/"

[workspace]
members = ["tools/build_helper"]

[workspace.package]
version = "0.1.0-dev"

[profile.dev]
opt-level = 0
debug = true
split-debuginfo = "unpacked"
codegen-units = 64
incremental = true
lto = false
panic = "unwind"

[profile.release]
opt-level = "z"
debug = false
split-defoinfo = "off"
codegen-units = 1
incremental = false
lto = "thin"
panic = "abort"
strip = true

[build-dependencies]
# Just Enough VCS String Formatter
string_proc = { path = "../VersionControl/utils/string_proc/" }

chrono = "0.4"
toml = "0.9"

[dependencies]
# Just Enough VCS
just_enough_vcs = { path = "../VersionControl", features = ["all"] }

# Error
thiserror = "2.0.17"

# Serialize
serde = { version = "1", features = ["derive"] }
serde_json = "1"

# Command Line
clap = { version = "4.5", features = ["derive"] }

# Time
chrono = "0.4"

# Logging
log = "0.4"
env_logger = "0.11"

# Async
tokio = { version = "1", features = ["full"] }

# Display
colored = "3.0"
strip-ansi-escapes = "0.2.1"

# Terminal
crossterm = "0.27"

# i18n
rust-i18n = "3"

# Regex
regex = "1.12.1"

# File & Directory
walkdir = "2.5.0"
dirs = "6.0.0"
