[package]
name = "just_enough_vcs_cli"
edition = "2024"

[workspace]
members = ["crates/build_helper"]

[workspace.package]
version = "0.1.0"

[profile.dev]
opt-level = 0
debug = true
split-debuginfo = "unpacked"
codegen-units = 16
incremental = true
lto = false
panic = "unwind"

[profile.release]
opt-level = 3
debug = false
split-debuginfo = "off"
codegen-units = 1
incremental = false
lto = "fat"
panic = "abort"
strip = "symbols"

[dependencies]
# Just Enough VCS
just_enough_vcs = { git = "https://github.com/JustEnoughVCS/VersionControl", features = [
    "all",
] }

# Command Line
clap = { version = "4.5", features = ["derive"] }

# Time
chrono = "0.4"

# Logging
log = "0.4"
env_logger = "0.11"

# Async
tokio = { version = "1", features = ["full"] }

# Color
colored = "2.0"

# i18n
rust-i18n = "3"

# Regex
regex = "1.12.1"
