################
### Commands ###
################

[cmd.status]
node = "status"
type = "cmds::status::JVStatusCommand"

#################
### Renderers ###
#################

# Default Renderer
[renderer.default]
name = "default"
type = "Renderer"

# Json Renderer
[renderer.json]
name = "json"
type = "crate::renderers::json::JVResultJsonRenderer"

[renderer.json_pretty]
name = "json-pretty"
type = "crate::renderers::json_pretty::JVResultPrettyJsonRenderer"

####################
### Auto-Collect ###
####################

[collect.outputs]
path = "src/outputs.rs"

[collect.inputs]
path = "src/inputs.rs"

[collect.cmds]
path = "src/cmds.rs"

[collect.arguments]
path = "src/arguments.rs"

[collect.renderers]
path = "src/renderers.rs"
