################
### Commands ###
################

# The system will automatically register commands under ./src/cmds/.
# This section is mainly for registering commands not in the automatic registration directory.

# [cmd.name]
# node = "name"
# type = "your_command::JVUnknownCommand"

#################
### Renderers ###
#################

# Only register renderers here that need to be overridden using the `--renderer` flag.
# After registration, you can use the format `command --renderer renderer_name` to override the renderer.

# Json Renderer
[renderer.json]
name = "json"
type = "crate::cmds::r#override::renderer::json"

[renderer.json_pretty]
name = "json-pretty"
type = "crate::cmds::r#override::renderer::json_pretty"

####################
### Auto-Collect ###
####################

[collect.args]
path = "src/cmds/arg.rs"

[collect.cmds]
path = "src/cmds/cmd.rs"

[collect.collects]
path = "src/cmds/collect.rs"

[collect.inputs]
path = "src/cmds/in.rs"

[collect.outputs]
path = "src/cmds/out.rs"

[collect.renderers]
path = "src/cmds/renderer.rs"

[collect.override_renderers]
path = "src/cmds/override/renderer.rs"
