################
### Commands ###
################

# The system will automatically register commands under ./src/cmds/.
# This section is mainly for registering commands not in the automatic registration directory.

# [cmd.name]
# node = "name"
# type = "your_command::JVUnknownCommand"

#################
### Renderers ###
#################

# Only register renderers here that need to be overridden using the `--renderer` flag.
# After registration, you can use the format `command --renderer renderer_name` to override the renderer.

# Default Renderer
[renderer.default]
name = "default"
type = "Renderer"

# Json Renderer
[renderer.json]
name = "json"
type = "crate::renderers::json::JVResultJsonRenderer"

[renderer.json_pretty]
name = "json-pretty"
type = "crate::renderers::json_pretty::JVResultPrettyJsonRenderer"

####################
### Auto-Collect ###
####################

[collect.outputs]
path = "src/outputs.rs"

[collect.inputs]
path = "src/inputs.rs"

[collect.cmds]
path = "src/cmds.rs"

[collect.arguments]
path = "src/arguments.rs"

[collect.renderers]
path = "src/renderers.rs"
